context: {}
stages:
  - name: mappingstage
    dependencies:
      - mapstage
    parameters:
      out: mergedfile.root
    scheduler: {$ref: '../schedulers/map-from-dep.yml'}
  - name: reducestage
    dependencies:
      - mapstage
    parameters:
      out: mergedfile.root
    scheduler: {$ref: '../schedulers/reduce-from-dep.yml'}